name: Trigger auto deployment for sender

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/sender-AutoDeployTrigger-c199cf7c-2458-40d3-ad06-6a4d88100948.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acarca.azurecr.io
          username: ${{ secrets.SENDER_REGISTRY_USERNAME }}
          password: ${{ secrets.SENDER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acarca.azurecr.io/g7cr-5paisa-net6:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SENDER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sender -g test-rg-ca --server acarca.azurecr.io --username  ${{ secrets.SENDER_REGISTRY_USERNAME }} --password ${{ secrets.SENDER_REGISTRY_PASSWORD }}
            az containerapp update -n sender -g test-rg-ca --image acarca.azurecr.io/g7cr-5paisa-net6:${{ github.sha }}
